apiVersion: apps/v1
kind: Deployment
metadata:
  name: api_example
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: api_example
        image: miaojinru/cicd-e2e-example:55
        ports:
        - containerPort: 8000