apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiexample
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: apiexample
        image: miaojinru/cicd-e2e-example:87
        ports:
        - containerPort: 8000

