apiVersion: v1
kind: Service
metadata:
  name: apiexample
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000